import { blue, cyan, deepPurple, green, grey, indigo, lightBlue, teal } from '@mui/material/colors';

export const Colors = [
    blue[300],
    blue[500],
    blue[700],
    indigo[300],
    indigo[500],
    indigo[700],
    green[300],
    green[500],
    green[700],
    grey[500],
    teal[300],
    teal[500],
    teal[700],
    cyan[300],
    cyan[500],
    cyan[700],
    lightBlue[500],
    deepPurple[500],
];

export const CLIENT_EVENT = {
    REDIRECT_UNIVERSAL: 'REDIRECT_UNIVERSAL',
    ID_CONVERSATION: 'ID_CONVERSATION',
    CHECK_AUTHEN: 'CHECK_AUTHEN',
    ON_OFF_MODAL: 'ON_OFF_MODAL',
    SYNC_DATA: 'SYNC_DATA',
    EDIT_MESSAGE: 'EDIT_MESSAGE',
    UPDATE_MESSAGE: 'UPDATE_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    ENTER_SEND_MESSAGE: 'ENTER_SEND_MESSAGE',
    CHANGE_SEND_MESSAGE: 'CHANGE_SEND_MESSAGE',
};

export const SOCKET_EVENT = {
    REQUEST_INVITE_USER: 'REQUEST_INVITE_USER',
    REQUEST_DELETE_CONVERSATION: 'REQUEST_DELETE_CONVERSATION',
    RESPONSE_INVITE_USERS: 'RESPONSE_INVITE_USERS',
    SYSTEM_NOTIFICATION: 'SYSTEM_NOTIFICATION',
    REQUEST_JOIN_CONVERSATIONS: 'REQUEST_JOIN_CONVERSATIONS',
    RESPONSE_JOIN_CONVERSATIONS: 'RESPONSE_JOIN_CONVERSATIONS',
    REQUEST_JOIN_CONVERSATION: 'REQUEST_JOIN_CONVERSATION',
    RESPONSE_JOIN_CONVERSATION: 'REQUEST_JOIN_CONVERSATION',
    RESPONSE_UPDATE_CONVERSATION: 'RESPONSE_UPDATE_CONVERSATION',
    RESPONSE_CREATE_CONVERSATION: 'RESPONSE_CREATE_CONVERSATION',
    RESPONSE_START_TYPING: 'RESPONSE_START_TYPING',
    RESPONSE_STOP_TYPING: 'RESPONSE_STOP_TYPING',
    RESPONSE_CREATE_MESSAGE: 'RESPONSE_CREATE_MESSAGE',
    DELETE_MESSAGE: 'RESPONSE_DELETE_MESSAGE',
    RESPONSE_LEAVE_CONVERSATION: 'RESPONSE_LEAVE_CONVERSATION',
    WOOF_WOOF: 'WOOF_WOOF',
    MEOW_MEOW: 'MEOW_MEOW',
};

export const TINY_MCE_KEY = '6hcownlou0x604gjtu5fy0d35zhd2osurzojn0n5eemutva8';
export const WORKSPACE_ID = '38647fbd-20a8-40ab-8292-b4828d636d29';
export const USER_STATUS = {
    PENDING: 'pending',
    NEWBIE: 'newbie',
    ACTIVE: 'active',
};
